import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import Cards from "../components/Cards";
import { fetchCoffeeStores } from "../lib/coffe-store-data-fetch";
// import coffeeStoresData from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  
const coffeeStores= await fetchCoffeeStores();
  return {
    props: {
      coffeeStores,
    },
  };
}


export default function Home(props) {
  const handleOnBannerButtonClick = () => {
    console.log("Hi Banner Button Clicked");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText="View Store nearby"
          handleOnClick={handleOnBannerButtonClick}
        />
        <div className={styles.heroImage}>
          {/* <Image src="/static/CoffeeDoddle-1.png" className={styles.mainImage} width={250} height={180}/> */}
        </div>

        {props.coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Kathmandu Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores.map((coffeeStore) => {
                return (
                  <Cards
                    key={coffeeStore.fsq_id}
                    name={coffeeStore.name}
                    imgUrl={coffeeStore.imgUrl || "https://images.unsplash.com/photo-1619970291259-3511cbadc5b1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80"}
                    href={`/coffee-shop/${coffeeStore.fsq_id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
